# The desktop file and icon should be in snap/gui folder, and are automatically copied.
# See "Launcher and desktop integration" in https://tutorials.ubuntu.com/tutorial/snap-a-website#6

name: numpyviewer
version: '0.5'
summary: Convenient viewer for numpy files.
description: |
  See https://github.com/ArendJanKramer/Qt-ENVI-Numpy-Viewer.

grade: stable
confinement: strict

base: core18

apps:
  numpyviewer:
    command: bin/desktop-launch $SNAP/usr/local/bin/numpyviewer
    plugs:
      - network
      - network-bind
      - unity7
      - home
      - opengl
parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
      - zlib1g
      - zlib1g-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  application:
    plugin: qmake
    project-files: ["numpyviewer.pro"]
    source: .
    build-packages:
      - qtbase5-dev
      - libqt5charts5-dev
      - libqt5svg5-dev
    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - libqt5gui5
      - libqt5charts5
      - libqt5svg5
    after:
      - desktop-qt5
